### ISSUE TITLE
Providing feedback

### ISSUE THREAD

**Issue by omaciel** [ldjebran/robozilla#1]
Hi @ldjebran,

I took a look at the output generated by your script but when you asked me to take a look at your project, I forgot to ask you for some context :) Is this what we would run ahead of running a test suite to fetch the Bugzilla issues (and their statuses) so that we can exclude tests affected by `WONTFIX` issues? If so, then 👍 

I wasn't sure if you wanted me to also review the code, but if you do, please let me know :)

**Comment by ldjebran** [comment]
Hi @omaciel , yes you guessed, the main purpose is to find WONTFIX issues by scanning the code, and perhaps in the future some other things as far as we provide handlers for that.

other usage for example you want to find test functions with ON_QA status to launch them,
or for code maintenance in the first stage concerning bugs status
