### ISSUE TITLE
Log exceptions while connecting to API

### ISSUE THREAD

**Issue by renzon** [ldjebran/robozilla#25]
Get bug data mask all exceptions from such connection. A warning message can be logged so users can be aware of connection problem.

**Comment by ldjebran** [comment]
@renzon connection problems an exception is raised

**Comment by renzon** [comment]
@ldjebran is authentication mandatory in roboziila? I was able to make call without authentication on robottelo. The only problem some fields, like flags, are not available on this case.

**Comment by ldjebran** [comment]
@renzon , the authentication is not mandatory, but for status retrieval and some private bugs the authentication is necessary
